---
title: "COVID-19 Portugal data"
output: 
  github_document:
    dev: svg
  html_document:
    dev: svg
  rmarkdown::html_vignette:
vignette: >
  %\VignetteIndexEntry{COVID19PT}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, eval=FALSE, include=FALSE}
rmarkdown::clean_site()
rmarkdown::render_site(quiet = TRUE)
```


```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
devtools::load_all()
library(pdftools)
library(rvest)
library(dplyr)
library(tibble)
library(DT)
library(anytime)
library(glue)
library(reshape2)
library(zoo)
library(xml2)
library(usethis)

library(ggplot2)

Sys.setlocale('LC_TIME', 'en_GB.UTF-8')
```



> R package with latest data scrapped from official sources

It downloads the [daily report](https://covid19.min-saude.pt/relatorio-de-situacao/) from DGS and stores this in data-friendly format under `/data` directory.

## Check for new reports

```{r, message=FALSE}
dat <- download.updated.pt()

dgs.pt.new     <- dat$dgs.pt
covid19.pt.new <- dat$cdc.eu
```

## Stores in the package

```{r}
# DGS PT
if (nrow(dgs.pt.new) != nrow(dgs.pt)) {
  dgs.pt <- dgs.pt.new
  usethis::use_data(dgs.pt, overwrite = TRUE)
  readr::write_csv(dgs.pt, path = '../data/dgs_pt.csv')
}

# EU CDC
covid19.pt <- tibble()
tryCatch(covid19.pt <- covid19.pt.data::covid19.pt, error = function(err) { })

if (nrow(covid19.pt.new) != nrow(covid19.pt)) {
  covid19.pt <- covid19.pt.new %>% distinct()
  usethis::use_data(covid19.pt, overwrite = TRUE)
  readr::write_csv(covid19.pt, path = '../data/covid19_pt.csv')
}

```

Data for Portugal

```{r, echo=FALSE}
dgs.pt %>% 
  reshape2::melt(id.vars = c('country', 'date'), variable.name = 'type') %>% 
  mutate(type = gsub('confirmed', 'Confirmed cases', type) %>%  gsub('deaths', 'Deaths', .) %>% gsub('recoveries', 'Recovered', .)) %>% 
  group_by(country, type) %>% 
  mutate(label = if_else(date == max(date), paste0(type, ': ', format(value, digits = 2, big.mark =',')), NA_character_)) %>% 
  ggplot(aes(x = date, y = value, color = type, label = label, fill = type)) +
    geom_line(size = 2) + 
    geom_point(size = 2.5) +
    ggrepel::geom_label_repel(color = 'white', 
                              segment.color = 'black', 
                              na.rm = TRUE, 
                              min.segment.length = 0, 
                              nudge_x = -2,
                              nudge_y = -.5,
                              segment.alpha = .8,
                              size = 3.5) +
    labs(x = 'Date', 
         y = 'Number of individuals',
         title = 'Individuals that were Infected, Recovered and Died',
         subtitle = 'Showing in logarithm scale (base 2)') +
    scale_y_continuous(trans = 'log2') +
    scale_color_viridis_d(end = .85) +
    scale_fill_viridis_d(end = .85) +
    theme_minimal() +
    theme(legend.position = 'none')
```


## Data from DGS

Only showing last 10 days

```{r, echo=FALSE}
dgs.pt %>% arrange(desc(date)) %>% top_n(10, date) %>% knitr::kable()
```

## Data from EU CDC updated

Only showing last 10 days

```{r, message=FALSE, echo=FALSE}
covid19.pt.new %>% head(10) %>% knitr::kable()
```




