on:
  schedule:
    - cron: '5/10 11-14 * * *'
    - cron:  '13 0-10,15-23 * * *'
  push:
    paths:
    - 'vignettes/*.Rmd'
    - '.github/workflows/main.yml'

jobs:
  build_rmd_site:
    runs-on: ubuntu-latest
    name: Build Rmd Site
    steps:
    - name: Checkout current repo
      uses: actions/checkout@v2
      with:
        path: repo
        token: ${{ secrets.token }}
    - name: Get current directory and files
      run: |
        pwd
        ls repo
    - name: Build html
      id: hello
      uses: averissimo/buid-r-docker-action@master
    # Use the output from the `hello` step
    - name: Commit changes
      run: |
        cd repo
        ls
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs README.md data
        if [ -d README_files ]; then git add README_files; fi
        if [ "$(git log --oneline --since='00:01' | wc -l)" -gt 0 ] && $(git log -n 1 --oneline | grep -q 'Update site (automatic)'); then
          echo "ammending"
          git commit --amend -m "Update site (automatic)" || echo "Nothing to update"
        else
          echo "new commit"
          git log --oneline --since='00:01'
          echo "number of commits since 00:01 $(git log --oneline --since='00:01' | wc -l)"
          git log -n 1 --oneline
          git log -n 1 --oneline | grep 'Update site (automatic)'
          echo ""
          git commit -m "Update site (automatic)" || echo "Nothing to update"
        fi
        git status
    - name: Push changes
      uses: ad-m/github-push-action@fe38f0a751bf9149f0270cc1fe20bf9156854365
      with:
        directory: repo
        force: true
        repository: averissimo/covid19.pt.data
        github_token: ${{ secrets.token }}
